{
  parserClass="com.plicku.flowla.plugin.parser.FlowlaParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Flowla"
  psiImplClassSuffix="Impl"
  psiPackage="com.plicku.flowla.plugin.psi"
  psiImplPackage="com.plicku.flowla.plugin.impl"

  elementTypeHolderClass="com.plicku.flowla.plugin.psi.FlowlaTypes"
  elementTypeClass="com.plicku.flowla.plugin.psi.FlowlaElementType"
  tokenTypeClass="com.plicku.flowla.plugin.psi.FlowlaTokenType"
}

flowlaFile ::= item_*

private item_ ::= (steps|COMMENT|CRLF|[""])

steps ::= step*
step ::= [""]step_keyword [stepname] [multiline_arg]

